services:
  mariadb:
    image: mariadb
    container_name: yorm_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yorm
      MYSQL_DATABASE: yorm
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
